Add check if build.board is uppercase

diff --git a/.github/workflows/boards.yml b/.github/workflows/boards.yml
--- a/.github/workflows/boards.yml
+++ b/.github/workflows/boards.yml
@@ -45,6 +45,16 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v3
 
+      - name: Check if build.board is uppercase
+        run: |
+          board_name=$(echo "espressif:pltf:esp32" | awk -F':' '{print $NF}')
+          if grep -q "^$board_name.build.board=[A-Z0-9_]*$" boards.txt; then
+            echo "$board_name.build.board is valid.";
+          else
+            echo "Error: $board_name.build.board is not uppercase!";
+            exit 1;
+          fi
+
       - name: Compile sketch
         uses: P-R-O-C-H-Y/compile-sketches@main
         with:
